# coding: utf-8

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


# solution = 4613732

total = 0
curr = 1
prev = 0
while curr < 4000000:
    curr = curr + prev
    prev = curr - prev
    print(curr)
    if curr % 2 == 0:
        total = total + curr
print(f"total {total}")
